//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class dish
    {
        public System.Guid id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public System.Guid type_id { get; set; }
        public Nullable<System.Guid> unit_id { get; set; }
        public Nullable<System.Guid> group_id { get; set; }
        public System.Guid branch_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> original_price { get; set; }
        public Nullable<decimal> number_in_stock { get; set; }
        public Nullable<decimal> weight { get; set; }
        public bool allow_sale_direct { get; set; }
        public string avatar { get; set; }
        public Nullable<decimal> min_in_stock { get; set; }
        public Nullable<decimal> max_in_stock { get; set; }
        public string description { get; set; }
        public string note_in_order { get; set; }
        public System.Guid create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.Guid> update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.Guid> delete_by { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual dish_group dish_group { get; set; }
        public virtual dish_type dish_type { get; set; }
        public virtual unit unit { get; set; }
    }
}
