//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.branch_employee = new HashSet<branch_employee>();
            this.users = new HashSet<user>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public bool gender { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public byte[] image { get; set; }
        public string address { get; set; }
        public string id_card { get; set; }
        public Nullable<System.Guid> location_id { get; set; }
        public System.DateTime start_working_date { get; set; }
        public Nullable<System.DateTime> end_working_date { get; set; }
        public System.Guid contract_type_code { get; set; }
        public System.Guid create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.Guid> update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.Guid> delete_by { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<branch_employee> branch_employee { get; set; }
        public virtual contract_type contract_type { get; set; }
        public virtual location location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
    }
}
