//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class fanpage_analyst
    {
        public System.Guid id { get; set; }
        public string fanpage_id { get; set; }
        public int likes { get; set; }
        public int follows { get; set; }
        public int reactions { get; set; }
        public System.DateTime datetime { get; set; }
    
        public virtual fanpage fanpage { get; set; }
    }
}
