//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class fanpage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fanpage()
        {
            this.fanpage_analyst = new HashSet<fanpage_analyst>();
            this.fanpage_post = new HashSet<fanpage_post>();
            this.fanpage_post_schedule = new HashSet<fanpage_post_schedule>();
            this.fanpage_user_management = new HashSet<fanpage_user_management>();
        }
    
        public string id { get; set; }
        public string user_name { get; set; }
        public string display_name { get; set; }
        public string category { get; set; }
        public string avatar_picture { get; set; }
        public string wall_picture { get; set; }
        public string address { get; set; }
        public string introduction { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public int likes { get; set; }
        public int follows { get; set; }
        public int reactions { get; set; }
        public System.Guid create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.Guid> update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.Guid> delete_by { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fanpage_analyst> fanpage_analyst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fanpage_post> fanpage_post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fanpage_post_schedule> fanpage_post_schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fanpage_user_management> fanpage_user_management { get; set; }
    }
}
