//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class fanpage_post_schedule
    {
        public System.Guid id { get; set; }
        public string fanpage_id { get; set; }
        public string post_id { get; set; }
        public bool is_published { get; set; }
        public Nullable<System.DateTime> publish_time { get; set; }
        public string message { get; set; }
        public string source { get; set; }
        public string link { get; set; }
        public string description { get; set; }
        public string caption { get; set; }
        public string picture { get; set; }
        public string type { get; set; }
        public System.DateTime time_to_post { get; set; }
        public bool status { get; set; }
        public System.Guid create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.Guid> update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.Guid> delete_by { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
    
        public virtual facebook_post_type facebook_post_type { get; set; }
        public virtual fanpage fanpage { get; set; }
    }
}
