//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ga_account
    {
        public string view_id { get; set; }
        public string view_name { get; set; }
        public string property_id { get; set; }
        public string property_name { get; set; }
        public string acc_id { get; set; }
        public string acc_name { get; set; }
        public string table_id { get; set; }
        public System.Guid create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.Guid> update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.Guid> delete_by { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
        public string api_key { get; set; }
        public string client_id { get; set; }
        public string secret_id { get; set; }
    }
}
