//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ga_user_type
    {
        public System.Guid id { get; set; }
        public string ga_id { get; set; }
        public byte day { get; set; }
        public byte month { get; set; }
        public short year { get; set; }
        public int new_user { get; set; }
        public int return_user { get; set; }
        public int user { get; set; }
        public int sessions { get; set; }
        public double bounces { get; set; }
        public double bounce_rate { get; set; }
        public double entrances { get; set; }
        public double pageviews { get; set; }
    }
}
