//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class good
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public good()
        {
            this.inventory_goods = new HashSet<inventory_goods>();
            this.stock_in_detail = new HashSet<stock_in_detail>();
            this.stock_out_detail = new HashSet<stock_out_detail>();
            this.stock_tranfer_detail = new HashSet<stock_tranfer_detail>();
        }
    
        public System.Guid id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<System.Guid> unit_id { get; set; }
        public Nullable<System.Guid> group_id { get; set; }
        public Nullable<decimal> org_price { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> number_in_stock { get; set; }
        public string avatar { get; set; }
        public decimal weight { get; set; }
        public string description { get; set; }
        public Nullable<decimal> min_in_stock { get; set; }
        public Nullable<decimal> max_in_stock { get; set; }
        public string note_in_order { get; set; }
        public System.Guid create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.Guid> update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.Guid> delete_by { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
    
        public virtual goods_group goods_group { get; set; }
        public virtual unit unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_goods> inventory_goods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stock_in_detail> stock_in_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stock_out_detail> stock_out_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stock_tranfer_detail> stock_tranfer_detail { get; set; }
    }
}
