//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_goods
    {
        public System.Guid id { get; set; }
        public System.Guid branch_id { get; set; }
        public System.Guid goods_id { get; set; }
        public double total { get; set; }
        public System.DateTime last_update { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual good good { get; set; }
    }
}
