//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class leave
    {
        public System.Guid id { get; set; }
        public string title { get; set; }
        public System.Guid user_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public short duration { get; set; }
        public System.Guid leave_type_id { get; set; }
        public System.Guid assignee { get; set; }
        public string comment { get; set; }
        public System.DateTime create_date { get; set; }
    
        public virtual leave_type leave_type { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
