//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.order_detail = new HashSet<order_detail>();
        }
    
        public System.Guid id { get; set; }
        public string code { get; set; }
        public System.Guid customer_id { get; set; }
        public decimal total_price { get; set; }
        public decimal discount { get; set; }
        public string notes { get; set; }
        public bool is_delivery { get; set; }
        public Nullable<System.Guid> deliver_id { get; set; }
        public decimal deliver_fee { get; set; }
        public Nullable<System.DateTime> deliver_receive_time { get; set; }
        public Nullable<System.DateTime> deliver_finish_time { get; set; }
        public Nullable<byte> delivery_status { get; set; }
        public string order_status { get; set; }
        public string order_resason { get; set; }
        public System.Guid branch_id { get; set; }
        public System.Guid create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.Guid> update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.Guid> delete_by { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
        public decimal dept { get; set; }
        public decimal payable { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual delivery_status delivery_status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_detail> order_detail { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
