//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class role_detail
    {
        public System.Guid id { get; set; }
        public System.Guid role_id { get; set; }
        public string function_code { get; set; }
    
        public virtual function function { get; set; }
        public virtual role role { get; set; }
    }
}
