//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_tranfer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stock_tranfer()
        {
            this.stock_tranfer_detail = new HashSet<stock_tranfer_detail>();
        }
    
        public System.Guid id { get; set; }
        public string code { get; set; }
        public System.Guid branch_from { get; set; }
        public System.Guid branch_to { get; set; }
        public System.Guid empl_id { get; set; }
        public System.DateTime date_tranfer { get; set; }
        public string reason { get; set; }
        public string notes { get; set; }
        public System.Guid create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.Guid> update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.Guid> delete_by { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual branch branch1 { get; set; }
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stock_tranfer_detail> stock_tranfer_detail { get; set; }
    }
}
