//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_tranfer_detail
    {
        public System.Guid id { get; set; }
        public System.Guid stock_tranfer_id { get; set; }
        public System.Guid goods_id { get; set; }
        public decimal number { get; set; }
    
        public virtual stock_tranfer stock_tranfer { get; set; }
        public virtual good good { get; set; }
    }
}
