//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_out_detail
    {
        public System.Guid id { get; set; }
        public System.Guid stock_out_id { get; set; }
        public System.Guid product_id { get; set; }
        public decimal number { get; set; }
        public decimal price { get; set; }
    
        public virtual product product { get; set; }
        public virtual stock_out stock_out { get; set; }
    }
}
