//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_dept_history
    {
        public System.Guid id { get; set; }
        public string code { get; set; }
        public string type { get; set; }
        public System.Guid supplier_id { get; set; }
        public decimal money_pay { get; set; }
        public System.DateTime date { get; set; }
        public decimal money_left { get; set; }
    }
}
